name:                aoc2019
version:             0.1.0.0
github:              "gillchristian/advent-of-code"
license:             MIT

description:         Advent of Code 2019 solutions

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

dependencies:
- base >= 4.7 && < 5
- containers
- split

data-files: inputs/*.txt

library:
  source-dirs: src
  generated-other-modules: Paths_aoc2019

executables:
  aoc2019-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019
    other-modules:
    - Paths_aoc2019

tests:
  aoc2019-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019
