name:                aoc2019
version:             0.1.0.0
github:              "gillchristian/advent-of-code"
license:             MIT

description:         Advent of Code 2019 solutions

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src

executables:
  aoc2019-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019

tests:
  aoc2019-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019
